Update the OBS systemsmanagement:Agama:Devel GPG key (#3334)
## Problem

- The systemsmanagement:Agama:Devel GPG key expired
- Calling `rpm` prints ugly errors:
```console
agama:~ # rpm -q agama
error: Key acaa9cf7e6e5a213 (systemsmanagement OBS Project <systemsmanagement@build.opensuse.org>) expired on 2026-02-13 10:36:19
error: Key acaa9cf7e6e5a213 (systemsmanagement OBS Project <systemsmanagement@build.opensuse.org>) expired on 2026-02-13 10:36:19
agama-19+54.3c73f2f0f-386.1.x86_64
```

## Solution

- Update the key, it was already updated in OBS
- Was downloaded with
  ```
curl
"https://build.opensuse.org/projects/systemsmanagement:Agama:Devel/signing_keys/download?kind=gpg"`
  ```